[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChenSignatures = "4efb4129-5e83-47d2-926d-947c0e6cb76d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
